package com.antigenomics.migmap

import com.antigenomics.migmap.io.ClonotypeSerializer
import com.antigenomics.migmap.analysis.Analysis

def cli = new CliBuilder(usage: "Correct [options] input.bin output_prefix\n" +
        "'input.bin' is a binary output file generated by MIGMAP with --write-binary option")

def opt = cli.parse(args)

if (opt.h || opt == null || opt.arguments().size() != 2) {
    cli.usage()
    System.exit(3)
}

def inputFile = opt.arguments()[0], outputPrefix = opt.arguments()[1]

def clonotypes = ClonotypeSerializer.load(new FileInputStream(inputFile))

def postAnalysis = new Analysis(clonotypes)

postAnalysis.generateHypermutationTable(outputPrefix + ".shm.txt")
postAnalysis.generateClonotypeTree(outputPrefix)